
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ContentItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ContentItem
 * 
 */
export type ContentItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ContentItemPayload>

export type AggregateContentItem = {
  _count: ContentItemCountAggregateOutputType | null
  _avg: ContentItemAvgAggregateOutputType | null
  _sum: ContentItemSumAggregateOutputType | null
  _min: ContentItemMinAggregateOutputType | null
  _max: ContentItemMaxAggregateOutputType | null
}

export type ContentItemAvgAggregateOutputType = {
  duration: number | null
}

export type ContentItemSumAggregateOutputType = {
  duration: number | null
}

export type ContentItemMinAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.ContentType | null
  energy: $Enums.Energy | null
  duration: number | null
  createdAt: Date | null
}

export type ContentItemMaxAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.ContentType | null
  energy: $Enums.Energy | null
  duration: number | null
  createdAt: Date | null
}

export type ContentItemCountAggregateOutputType = {
  id: number
  title: number
  type: number
  energy: number
  moods: number
  duration: number
  createdAt: number
  _all: number
}


export type ContentItemAvgAggregateInputType = {
  duration?: true
}

export type ContentItemSumAggregateInputType = {
  duration?: true
}

export type ContentItemMinAggregateInputType = {
  id?: true
  title?: true
  type?: true
  energy?: true
  duration?: true
  createdAt?: true
}

export type ContentItemMaxAggregateInputType = {
  id?: true
  title?: true
  type?: true
  energy?: true
  duration?: true
  createdAt?: true
}

export type ContentItemCountAggregateInputType = {
  id?: true
  title?: true
  type?: true
  energy?: true
  moods?: true
  duration?: true
  createdAt?: true
  _all?: true
}

export type ContentItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContentItem to aggregate.
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContentItems to fetch.
   */
  orderBy?: Prisma.ContentItemOrderByWithRelationInput | Prisma.ContentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ContentItems
  **/
  _count?: true | ContentItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContentItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContentItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContentItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContentItemMaxAggregateInputType
}

export type GetContentItemAggregateType<T extends ContentItemAggregateArgs> = {
      [P in keyof T & keyof AggregateContentItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContentItem[P]>
    : Prisma.GetScalarType<T[P], AggregateContentItem[P]>
}




export type ContentItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContentItemWhereInput
  orderBy?: Prisma.ContentItemOrderByWithAggregationInput | Prisma.ContentItemOrderByWithAggregationInput[]
  by: Prisma.ContentItemScalarFieldEnum[] | Prisma.ContentItemScalarFieldEnum
  having?: Prisma.ContentItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContentItemCountAggregateInputType | true
  _avg?: ContentItemAvgAggregateInputType
  _sum?: ContentItemSumAggregateInputType
  _min?: ContentItemMinAggregateInputType
  _max?: ContentItemMaxAggregateInputType
}

export type ContentItemGroupByOutputType = {
  id: string
  title: string
  type: $Enums.ContentType
  energy: $Enums.Energy
  moods: $Enums.Mood[]
  duration: number
  createdAt: Date
  _count: ContentItemCountAggregateOutputType | null
  _avg: ContentItemAvgAggregateOutputType | null
  _sum: ContentItemSumAggregateOutputType | null
  _min: ContentItemMinAggregateOutputType | null
  _max: ContentItemMaxAggregateOutputType | null
}

type GetContentItemGroupByPayload<T extends ContentItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContentItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContentItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContentItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContentItemGroupByOutputType[P]>
      }
    >
  >



export type ContentItemWhereInput = {
  AND?: Prisma.ContentItemWhereInput | Prisma.ContentItemWhereInput[]
  OR?: Prisma.ContentItemWhereInput[]
  NOT?: Prisma.ContentItemWhereInput | Prisma.ContentItemWhereInput[]
  id?: Prisma.StringFilter<"ContentItem"> | string
  title?: Prisma.StringFilter<"ContentItem"> | string
  type?: Prisma.EnumContentTypeFilter<"ContentItem"> | $Enums.ContentType
  energy?: Prisma.EnumEnergyFilter<"ContentItem"> | $Enums.Energy
  moods?: Prisma.EnumMoodNullableListFilter<"ContentItem">
  duration?: Prisma.IntFilter<"ContentItem"> | number
  createdAt?: Prisma.DateTimeFilter<"ContentItem"> | Date | string
}

export type ContentItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  energy?: Prisma.SortOrder
  moods?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContentItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ContentItemWhereInput | Prisma.ContentItemWhereInput[]
  OR?: Prisma.ContentItemWhereInput[]
  NOT?: Prisma.ContentItemWhereInput | Prisma.ContentItemWhereInput[]
  title?: Prisma.StringFilter<"ContentItem"> | string
  type?: Prisma.EnumContentTypeFilter<"ContentItem"> | $Enums.ContentType
  energy?: Prisma.EnumEnergyFilter<"ContentItem"> | $Enums.Energy
  moods?: Prisma.EnumMoodNullableListFilter<"ContentItem">
  duration?: Prisma.IntFilter<"ContentItem"> | number
  createdAt?: Prisma.DateTimeFilter<"ContentItem"> | Date | string
}, "id">

export type ContentItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  energy?: Prisma.SortOrder
  moods?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ContentItemCountOrderByAggregateInput
  _avg?: Prisma.ContentItemAvgOrderByAggregateInput
  _max?: Prisma.ContentItemMaxOrderByAggregateInput
  _min?: Prisma.ContentItemMinOrderByAggregateInput
  _sum?: Prisma.ContentItemSumOrderByAggregateInput
}

export type ContentItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContentItemScalarWhereWithAggregatesInput | Prisma.ContentItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContentItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContentItemScalarWhereWithAggregatesInput | Prisma.ContentItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ContentItem"> | string
  title?: Prisma.StringWithAggregatesFilter<"ContentItem"> | string
  type?: Prisma.EnumContentTypeWithAggregatesFilter<"ContentItem"> | $Enums.ContentType
  energy?: Prisma.EnumEnergyWithAggregatesFilter<"ContentItem"> | $Enums.Energy
  moods?: Prisma.EnumMoodNullableListFilter<"ContentItem">
  duration?: Prisma.IntWithAggregatesFilter<"ContentItem"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ContentItem"> | Date | string
}

export type ContentItemCreateInput = {
  id?: string
  title: string
  type: $Enums.ContentType
  energy: $Enums.Energy
  moods?: Prisma.ContentItemCreatemoodsInput | $Enums.Mood[]
  duration: number
  createdAt?: Date | string
}

export type ContentItemUncheckedCreateInput = {
  id?: string
  title: string
  type: $Enums.ContentType
  energy: $Enums.Energy
  moods?: Prisma.ContentItemCreatemoodsInput | $Enums.Mood[]
  duration: number
  createdAt?: Date | string
}

export type ContentItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumContentTypeFieldUpdateOperationsInput | $Enums.ContentType
  energy?: Prisma.EnumEnergyFieldUpdateOperationsInput | $Enums.Energy
  moods?: Prisma.ContentItemUpdatemoodsInput | $Enums.Mood[]
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContentItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumContentTypeFieldUpdateOperationsInput | $Enums.ContentType
  energy?: Prisma.EnumEnergyFieldUpdateOperationsInput | $Enums.Energy
  moods?: Prisma.ContentItemUpdatemoodsInput | $Enums.Mood[]
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContentItemCreateManyInput = {
  id?: string
  title: string
  type: $Enums.ContentType
  energy: $Enums.Energy
  moods?: Prisma.ContentItemCreatemoodsInput | $Enums.Mood[]
  duration: number
  createdAt?: Date | string
}

export type ContentItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumContentTypeFieldUpdateOperationsInput | $Enums.ContentType
  energy?: Prisma.EnumEnergyFieldUpdateOperationsInput | $Enums.Energy
  moods?: Prisma.ContentItemUpdatemoodsInput | $Enums.Mood[]
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContentItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumContentTypeFieldUpdateOperationsInput | $Enums.ContentType
  energy?: Prisma.EnumEnergyFieldUpdateOperationsInput | $Enums.Energy
  moods?: Prisma.ContentItemUpdatemoodsInput | $Enums.Mood[]
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EnumMoodNullableListFilter<$PrismaModel = never> = {
  equals?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel> | null
  has?: $Enums.Mood | Prisma.EnumMoodFieldRefInput<$PrismaModel> | null
  hasEvery?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  hasSome?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ContentItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  energy?: Prisma.SortOrder
  moods?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContentItemAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type ContentItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  energy?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContentItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  energy?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ContentItemSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type ContentItemCreatemoodsInput = {
  set: $Enums.Mood[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumContentTypeFieldUpdateOperationsInput = {
  set?: $Enums.ContentType
}

export type EnumEnergyFieldUpdateOperationsInput = {
  set?: $Enums.Energy
}

export type ContentItemUpdatemoodsInput = {
  set?: $Enums.Mood[]
  push?: $Enums.Mood | $Enums.Mood[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type ContentItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  energy?: boolean
  moods?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["contentItem"]>

export type ContentItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  energy?: boolean
  moods?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["contentItem"]>

export type ContentItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  energy?: boolean
  moods?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["contentItem"]>

export type ContentItemSelectScalar = {
  id?: boolean
  title?: boolean
  type?: boolean
  energy?: boolean
  moods?: boolean
  duration?: boolean
  createdAt?: boolean
}

export type ContentItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "type" | "energy" | "moods" | "duration" | "createdAt", ExtArgs["result"]["contentItem"]>

export type $ContentItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ContentItem"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    type: $Enums.ContentType
    energy: $Enums.Energy
    moods: $Enums.Mood[]
    duration: number
    createdAt: Date
  }, ExtArgs["result"]["contentItem"]>
  composites: {}
}

export type ContentItemGetPayload<S extends boolean | null | undefined | ContentItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContentItemPayload, S>

export type ContentItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContentItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContentItemCountAggregateInputType | true
  }

export interface ContentItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ContentItem'], meta: { name: 'ContentItem' } }
  /**
   * Find zero or one ContentItem that matches the filter.
   * @param {ContentItemFindUniqueArgs} args - Arguments to find a ContentItem
   * @example
   * // Get one ContentItem
   * const contentItem = await prisma.contentItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContentItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ContentItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ContentItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContentItemFindUniqueOrThrowArgs} args - Arguments to find a ContentItem
   * @example
   * // Get one ContentItem
   * const contentItem = await prisma.contentItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContentItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContentItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContentItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemFindFirstArgs} args - Arguments to find a ContentItem
   * @example
   * // Get one ContentItem
   * const contentItem = await prisma.contentItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContentItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ContentItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContentItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemFindFirstOrThrowArgs} args - Arguments to find a ContentItem
   * @example
   * // Get one ContentItem
   * const contentItem = await prisma.contentItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContentItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContentItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ContentItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContentItems
   * const contentItems = await prisma.contentItem.findMany()
   * 
   * // Get first 10 ContentItems
   * const contentItems = await prisma.contentItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contentItemWithIdOnly = await prisma.contentItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContentItemFindManyArgs>(args?: Prisma.SelectSubset<T, ContentItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ContentItem.
   * @param {ContentItemCreateArgs} args - Arguments to create a ContentItem.
   * @example
   * // Create one ContentItem
   * const ContentItem = await prisma.contentItem.create({
   *   data: {
   *     // ... data to create a ContentItem
   *   }
   * })
   * 
   */
  create<T extends ContentItemCreateArgs>(args: Prisma.SelectSubset<T, ContentItemCreateArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ContentItems.
   * @param {ContentItemCreateManyArgs} args - Arguments to create many ContentItems.
   * @example
   * // Create many ContentItems
   * const contentItem = await prisma.contentItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContentItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ContentItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ContentItems and returns the data saved in the database.
   * @param {ContentItemCreateManyAndReturnArgs} args - Arguments to create many ContentItems.
   * @example
   * // Create many ContentItems
   * const contentItem = await prisma.contentItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ContentItems and only return the `id`
   * const contentItemWithIdOnly = await prisma.contentItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContentItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContentItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ContentItem.
   * @param {ContentItemDeleteArgs} args - Arguments to delete one ContentItem.
   * @example
   * // Delete one ContentItem
   * const ContentItem = await prisma.contentItem.delete({
   *   where: {
   *     // ... filter to delete one ContentItem
   *   }
   * })
   * 
   */
  delete<T extends ContentItemDeleteArgs>(args: Prisma.SelectSubset<T, ContentItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ContentItem.
   * @param {ContentItemUpdateArgs} args - Arguments to update one ContentItem.
   * @example
   * // Update one ContentItem
   * const contentItem = await prisma.contentItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContentItemUpdateArgs>(args: Prisma.SelectSubset<T, ContentItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ContentItems.
   * @param {ContentItemDeleteManyArgs} args - Arguments to filter ContentItems to delete.
   * @example
   * // Delete a few ContentItems
   * const { count } = await prisma.contentItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContentItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContentItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContentItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContentItems
   * const contentItem = await prisma.contentItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContentItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ContentItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContentItems and returns the data updated in the database.
   * @param {ContentItemUpdateManyAndReturnArgs} args - Arguments to update many ContentItems.
   * @example
   * // Update many ContentItems
   * const contentItem = await prisma.contentItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ContentItems and only return the `id`
   * const contentItemWithIdOnly = await prisma.contentItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContentItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContentItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ContentItem.
   * @param {ContentItemUpsertArgs} args - Arguments to update or create a ContentItem.
   * @example
   * // Update or create a ContentItem
   * const contentItem = await prisma.contentItem.upsert({
   *   create: {
   *     // ... data to create a ContentItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContentItem we want to update
   *   }
   * })
   */
  upsert<T extends ContentItemUpsertArgs>(args: Prisma.SelectSubset<T, ContentItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ContentItemClient<runtime.Types.Result.GetResult<Prisma.$ContentItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ContentItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemCountArgs} args - Arguments to filter ContentItems to count.
   * @example
   * // Count the number of ContentItems
   * const count = await prisma.contentItem.count({
   *   where: {
   *     // ... the filter for the ContentItems we want to count
   *   }
   * })
  **/
  count<T extends ContentItemCountArgs>(
    args?: Prisma.Subset<T, ContentItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContentItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ContentItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContentItemAggregateArgs>(args: Prisma.Subset<T, ContentItemAggregateArgs>): Prisma.PrismaPromise<GetContentItemAggregateType<T>>

  /**
   * Group by ContentItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContentItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContentItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContentItemGroupByArgs['orderBy'] }
      : { orderBy?: ContentItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContentItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContentItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ContentItem model
 */
readonly fields: ContentItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContentItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContentItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ContentItem model
 */
export interface ContentItemFieldRefs {
  readonly id: Prisma.FieldRef<"ContentItem", 'String'>
  readonly title: Prisma.FieldRef<"ContentItem", 'String'>
  readonly type: Prisma.FieldRef<"ContentItem", 'ContentType'>
  readonly energy: Prisma.FieldRef<"ContentItem", 'Energy'>
  readonly moods: Prisma.FieldRef<"ContentItem", 'Mood[]'>
  readonly duration: Prisma.FieldRef<"ContentItem", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ContentItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ContentItem findUnique
 */
export type ContentItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter, which ContentItem to fetch.
   */
  where: Prisma.ContentItemWhereUniqueInput
}

/**
 * ContentItem findUniqueOrThrow
 */
export type ContentItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter, which ContentItem to fetch.
   */
  where: Prisma.ContentItemWhereUniqueInput
}

/**
 * ContentItem findFirst
 */
export type ContentItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter, which ContentItem to fetch.
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContentItems to fetch.
   */
  orderBy?: Prisma.ContentItemOrderByWithRelationInput | Prisma.ContentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContentItems.
   */
  cursor?: Prisma.ContentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContentItems.
   */
  distinct?: Prisma.ContentItemScalarFieldEnum | Prisma.ContentItemScalarFieldEnum[]
}

/**
 * ContentItem findFirstOrThrow
 */
export type ContentItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter, which ContentItem to fetch.
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContentItems to fetch.
   */
  orderBy?: Prisma.ContentItemOrderByWithRelationInput | Prisma.ContentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContentItems.
   */
  cursor?: Prisma.ContentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContentItems.
   */
  distinct?: Prisma.ContentItemScalarFieldEnum | Prisma.ContentItemScalarFieldEnum[]
}

/**
 * ContentItem findMany
 */
export type ContentItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter, which ContentItems to fetch.
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContentItems to fetch.
   */
  orderBy?: Prisma.ContentItemOrderByWithRelationInput | Prisma.ContentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ContentItems.
   */
  cursor?: Prisma.ContentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContentItems.
   */
  skip?: number
  distinct?: Prisma.ContentItemScalarFieldEnum | Prisma.ContentItemScalarFieldEnum[]
}

/**
 * ContentItem create
 */
export type ContentItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * The data needed to create a ContentItem.
   */
  data: Prisma.XOR<Prisma.ContentItemCreateInput, Prisma.ContentItemUncheckedCreateInput>
}

/**
 * ContentItem createMany
 */
export type ContentItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ContentItems.
   */
  data: Prisma.ContentItemCreateManyInput | Prisma.ContentItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContentItem createManyAndReturn
 */
export type ContentItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * The data used to create many ContentItems.
   */
  data: Prisma.ContentItemCreateManyInput | Prisma.ContentItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContentItem update
 */
export type ContentItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * The data needed to update a ContentItem.
   */
  data: Prisma.XOR<Prisma.ContentItemUpdateInput, Prisma.ContentItemUncheckedUpdateInput>
  /**
   * Choose, which ContentItem to update.
   */
  where: Prisma.ContentItemWhereUniqueInput
}

/**
 * ContentItem updateMany
 */
export type ContentItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ContentItems.
   */
  data: Prisma.XOR<Prisma.ContentItemUpdateManyMutationInput, Prisma.ContentItemUncheckedUpdateManyInput>
  /**
   * Filter which ContentItems to update
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * Limit how many ContentItems to update.
   */
  limit?: number
}

/**
 * ContentItem updateManyAndReturn
 */
export type ContentItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * The data used to update ContentItems.
   */
  data: Prisma.XOR<Prisma.ContentItemUpdateManyMutationInput, Prisma.ContentItemUncheckedUpdateManyInput>
  /**
   * Filter which ContentItems to update
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * Limit how many ContentItems to update.
   */
  limit?: number
}

/**
 * ContentItem upsert
 */
export type ContentItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * The filter to search for the ContentItem to update in case it exists.
   */
  where: Prisma.ContentItemWhereUniqueInput
  /**
   * In case the ContentItem found by the `where` argument doesn't exist, create a new ContentItem with this data.
   */
  create: Prisma.XOR<Prisma.ContentItemCreateInput, Prisma.ContentItemUncheckedCreateInput>
  /**
   * In case the ContentItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContentItemUpdateInput, Prisma.ContentItemUncheckedUpdateInput>
}

/**
 * ContentItem delete
 */
export type ContentItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
  /**
   * Filter which ContentItem to delete.
   */
  where: Prisma.ContentItemWhereUniqueInput
}

/**
 * ContentItem deleteMany
 */
export type ContentItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContentItems to delete
   */
  where?: Prisma.ContentItemWhereInput
  /**
   * Limit how many ContentItems to delete.
   */
  limit?: number
}

/**
 * ContentItem without action
 */
export type ContentItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContentItem
   */
  select?: Prisma.ContentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContentItem
   */
  omit?: Prisma.ContentItemOmit<ExtArgs> | null
}
