
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumContentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentType | Prisma.EnumContentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentTypeFilter<$PrismaModel> | $Enums.ContentType
}

export type EnumEnergyFilter<$PrismaModel = never> = {
  equals?: $Enums.Energy | Prisma.EnumEnergyFieldRefInput<$PrismaModel>
  in?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnergyFilter<$PrismaModel> | $Enums.Energy
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumContentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentType | Prisma.EnumContentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentTypeWithAggregatesFilter<$PrismaModel> | $Enums.ContentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumContentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumContentTypeFilter<$PrismaModel>
}

export type EnumEnergyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Energy | Prisma.EnumEnergyFieldRefInput<$PrismaModel>
  in?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnergyWithAggregatesFilter<$PrismaModel> | $Enums.Energy
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnergyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnergyFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type EnumMoodFilter<$PrismaModel = never> = {
  equals?: $Enums.Mood | Prisma.EnumMoodFieldRefInput<$PrismaModel>
  in?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  notIn?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMoodFilter<$PrismaModel> | $Enums.Mood
}

export type EnumFeedbackNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Feedback | Prisma.EnumFeedbackFieldRefInput<$PrismaModel> | null
  in?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel> | $Enums.Feedback | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type EnumMoodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Mood | Prisma.EnumMoodFieldRefInput<$PrismaModel>
  in?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  notIn?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMoodWithAggregatesFilter<$PrismaModel> | $Enums.Mood
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMoodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMoodFilter<$PrismaModel>
}

export type EnumFeedbackNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Feedback | Prisma.EnumFeedbackFieldRefInput<$PrismaModel> | null
  in?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumFeedbackNullableWithAggregatesFilter<$PrismaModel> | $Enums.Feedback | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumContentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentType | Prisma.EnumContentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentTypeFilter<$PrismaModel> | $Enums.ContentType
}

export type NestedEnumEnergyFilter<$PrismaModel = never> = {
  equals?: $Enums.Energy | Prisma.EnumEnergyFieldRefInput<$PrismaModel>
  in?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnergyFilter<$PrismaModel> | $Enums.Energy
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedEnumContentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentType | Prisma.EnumContentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentType[] | Prisma.ListEnumContentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentTypeWithAggregatesFilter<$PrismaModel> | $Enums.ContentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumContentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumContentTypeFilter<$PrismaModel>
}

export type NestedEnumEnergyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Energy | Prisma.EnumEnergyFieldRefInput<$PrismaModel>
  in?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  notIn?: $Enums.Energy[] | Prisma.ListEnumEnergyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEnergyWithAggregatesFilter<$PrismaModel> | $Enums.Energy
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEnergyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEnergyFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumMoodFilter<$PrismaModel = never> = {
  equals?: $Enums.Mood | Prisma.EnumMoodFieldRefInput<$PrismaModel>
  in?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  notIn?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMoodFilter<$PrismaModel> | $Enums.Mood
}

export type NestedEnumFeedbackNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Feedback | Prisma.EnumFeedbackFieldRefInput<$PrismaModel> | null
  in?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel> | $Enums.Feedback | null
}

export type NestedEnumMoodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Mood | Prisma.EnumMoodFieldRefInput<$PrismaModel>
  in?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  notIn?: $Enums.Mood[] | Prisma.ListEnumMoodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMoodWithAggregatesFilter<$PrismaModel> | $Enums.Mood
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMoodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMoodFilter<$PrismaModel>
}

export type NestedEnumFeedbackNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Feedback | Prisma.EnumFeedbackFieldRefInput<$PrismaModel> | null
  in?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Feedback[] | Prisma.ListEnumFeedbackFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumFeedbackNullableWithAggregatesFilter<$PrismaModel> | $Enums.Feedback | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumFeedbackNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}


