
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ContentType = {
  MUSIC: 'MUSIC',
  READING: 'READING',
  GAME: 'GAME',
  OFFLINE_ACTIVITY: 'OFFLINE_ACTIVITY'
} as const

export type ContentType = (typeof ContentType)[keyof typeof ContentType]


export const Energy = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
} as const

export type Energy = (typeof Energy)[keyof typeof Energy]


export const Mood = {
  ANXIOUS: 'ANXIOUS',
  BORED: 'BORED',
  FOCUSED: 'FOCUSED',
  SAD: 'SAD',
  NOSTALGIC: 'NOSTALGIC'
} as const

export type Mood = (typeof Mood)[keyof typeof Mood]


export const Feedback = {
  UP: 'UP',
  DOWN: 'DOWN'
} as const

export type Feedback = (typeof Feedback)[keyof typeof Feedback]
